USE SocialNetwork
ALTER DATABASE SocialNetwork SET ALLOW_SNAPSHOT_ISOLATION ON;
ALTER DATABASE SocialNetwork SET ALLOW_SNAPSHOT_ISOLATION OFF;


SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED; --      гряз чт 
SET TRANSACTION ISOLATION LEVEL READ COMMITTED;   --      _______ изм извне
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;  -- (tr) _______ _________ нов стр
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;     -- (tr) _______ _________ _______
SET TRANSACTION ISOLATION LEVEL SNAPSHOT;         --  tr (tr) 

DELETE FROM dbo.Profiles WHERE ProfileName = 'ROGER';
INSERT INTO dbo.Profiles (ProfileName, ProfileAge) VALUES ('ROGER', 124286);
SELECT * FROM dbo.Profiles

BEGIN TRAN;
	SELECT * FROM dbo.Profiles
	UPDATE dbo.Profiles SET ProfileAge = 66666 WHERE ProfileName = 'ROGER';
	SELECT * FROM dbo.Profiles
--ROLLBACK TRAN;
COMMIT TRAN;
